/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import cliente.Client;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.json.JsonObject;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.SwingUtilities;
import javax.swing.border.LineBorder;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;
import protocolo.ClientProtocol;

/**
 *
 * @author pablo
 */
public class AlquilerSurf extends javax.swing.JPanel {

    /**
     * Panel que gestiona el Alquiler de tablas de surf, se muestra cuando en Principal se pusa en AlquilerKayak
     */
    String usuarioescuela;
     ClientProtocol cpl;
     String preciohora;
     String preciodia;
     String alquiler="tabla surf";
     String lista="aprob";
     boolean activo=false;
    
     static int width=958;
    static int height=725;
    
       
    public AlquilerSurf(String usuarioescuela){
         this.usuarioescuela=usuarioescuela;
        cpl=Client.getClientProtocol();
        initComponents();
        colocaValores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtxPrecioDia = new javax.swing.JTextField();
        jtxPrecioHora = new javax.swing.JTextField();
        labelLista = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        beditaHora = new javax.swing.JButton();
        beditaDia = new javax.swing.JButton();
        bAtras = new javax.swing.JButton();
        bGuardar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelSolicitudes = new javax.swing.JPanel();
        labelSolicitudes = new javax.swing.JLabel();
        jlNotif = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo-login.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("ALQUILER SURF");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Precio por hora:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Precio por día:");

        jtxPrecioDia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtxPrecioDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxPrecioDiaActionPerformed(evt);
            }
        });

        jtxPrecioHora.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtxPrecioHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxPrecioHoraActionPerformed(evt);
            }
        });

        labelLista.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelLista.setText("APROBADAS");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("€");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("€");

        beditaHora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pencil.png"))); // NOI18N
        beditaHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beditaHoraActionPerformed(evt);
            }
        });

        beditaDia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pencil.png"))); // NOI18N
        beditaDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beditaDiaActionPerformed(evt);
            }
        });

        bAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/atras.png"))); // NOI18N
        bAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAtrasActionPerformed(evt);
            }
        });

        bGuardar.setText("Guardar");
        bGuardar.setEnabled(false);
        bGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGuardarActionPerformed(evt);
            }
        });

        labelSolicitudes.setEnabled(false);
        labelSolicitudes.setOpaque(true);

        javax.swing.GroupLayout panelSolicitudesLayout = new javax.swing.GroupLayout(panelSolicitudes);
        panelSolicitudes.setLayout(panelSolicitudesLayout);
        panelSolicitudesLayout.setHorizontalGroup(
            panelSolicitudesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSolicitudesLayout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(labelSolicitudes)
                .addContainerGap(364, Short.MAX_VALUE))
        );
        panelSolicitudesLayout.setVerticalGroup(
            panelSolicitudesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSolicitudesLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(labelSolicitudes)
                .addContainerGap(463, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(panelSolicitudes);

        jlNotif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/notification.png"))); // NOI18N
        jlNotif.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bGuardar)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(beditaHora, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jtxPrecioDia, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jLabel5)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jtxPrecioHora, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(beditaDia, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel6)))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel4))))
                                .addGap(55, 55, 55)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bAtras)
                                .addGap(564, 564, 564)
                                .addComponent(labelLista)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(131, 131, 131)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlNotif)
                        .addGap(83, 83, 83))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(10, 10, 10)
                .addComponent(bAtras)
                .addGap(86, 86, 86)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jtxPrecioHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addComponent(beditaHora))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(beditaDia)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jtxPrecioDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)))
                .addGap(46, 46, 46)
                .addComponent(bGuardar)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jlNotif)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(labelLista)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 941, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 734, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtxPrecioDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxPrecioDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxPrecioDiaActionPerformed

    private void jtxPrecioHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxPrecioHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxPrecioHoraActionPerformed
  /**
     * Al pulsar en el botón para editar el precio de la hora, se pide un nuevo precio y se guarda en la variable global.
     * Se activa el botón de guardar.
     * @param evt 
     */
    private void beditaHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beditaHoraActionPerformed
         String spreciohora = JOptionPane.showInputDialog("Introduzca nuevo precio de la hora: ");
        if (spreciohora.equals("")) {
            JOptionPane.showMessageDialog(this, "No puede dejar el campo vacío", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            jtxPrecioHora.setText(spreciohora);
            preciohora=spreciohora;
            bGuardar.setEnabled(true);
        }
    }//GEN-LAST:event_beditaHoraActionPerformed
  /**
     * Cuando se pulsa el botón de atrás se vuelve a la pantalla principal
     * @param evt 
     */
    private void bAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAtrasActionPerformed
        PrincipalFrame f = (PrincipalFrame) SwingUtilities.windowForComponent(bAtras);
        Dimension ss = Toolkit.getDefaultToolkit().getScreenSize();
        f.setBounds(ss.width / 2 - Principal.width / 2,
                ss.height / 2 - Principal.height / 2,
                Principal.width, Principal.height);
        Principal pp = new Principal(usuarioescuela);
        f.setContentPane(pp);
        f.pack();
        f.setSize(958, 725);
        f.setVisible(true);        
    }//GEN-LAST:event_bAtrasActionPerformed
      /**
     * Este método es el que se encarga de mostrar las solicitudes de alquiler en el panel de la derecha.
     * Se obtienen las solicitudes y se crea un objeto Panel que será el que se va a mostrar.
     */
    private void initSolicitudes(){
         panelSolicitudes.setLayout(new BoxLayout(panelSolicitudes, BoxLayout.Y_AXIS));
          try {
     
         String nombre,telefono,cantidad,fecha,hora,factura,usuario;
         int icantidad,idalquiler,aprobado,cancelado;
         JSONObject respuesta = cpl.getAlquileres(usuarioescuela, "tabla surf");
            JSONArray array = respuesta.getJSONArray("alquileres");
           int solicitudes=0;
        for (int i = 0; i < array.length(); i++) {
           
                 JSONObject row = array.getJSONObject(i);
                 nombre=row.getString("nombre");
                 telefono=row.getString("telefono");
                 icantidad=row.getInt("cantidad");
                 cantidad=Integer.toString(icantidad);
                 fecha=row.getString("fecha");
                 hora=row.getString("hora");
                 factura=row.getString("factura");
                 usuario=row.getString("usuario");
                 idalquiler=row.getInt("idalquiler");
                 aprobado=row.getInt("aprobado");
                 cancelado=row.getInt("cancelado");
                 if(aprobado!=1 && cancelado!=1){
                     solicitudes++;
                 PanelSolicitud newPanel = new PanelSolicitud(nombre,telefono,cantidad,fecha,hora,factura,usuario,idalquiler,aprobado,cancelado,alquiler);
                panelSolicitudes.add(newPanel);
                //panelSolicitudes.revalidate();
                 }
            
        }
       
        panelSolicitudes.setVisible(true);
         } catch (JSONException ex) {
                 Logger.getLogger(AlquilerSurf.class.getName()).log(Level.SEVERE, null, ex);
             }
       
          
              //  MyBtnAction mba=new MyBtnAction(nombre);
             
             
         

    }
     /**
     * Este método es el que se encarga de mostrar las solicitudes aprobadas de alquiler en el panel de la derecha.
     * Se obtienen las solicitudes y se crea un objeto Panel que será el que se va a mostrar.
     */
    private void initAprobadas(){
      
         panelSolicitudes.setLayout(new BoxLayout(panelSolicitudes, BoxLayout.Y_AXIS));
          try {
     
         String nombre,telefono,cantidad,fecha,hora,factura,usuario;
         int icantidad,idalquiler,aprobado,cancelado,realizado;
         JSONObject respuesta = cpl.getAlquileres(usuarioescuela, "tabla surf");
            JSONArray array = respuesta.getJSONArray("alquileres");
           int solicitudes=0;
        for (int i = 0; i < array.length(); i++) {
           
                 JSONObject row = array.getJSONObject(i);
                 nombre=row.getString("nombre");
                 telefono=row.getString("telefono");
                 icantidad=row.getInt("cantidad");
                 cantidad=Integer.toString(icantidad);
                 fecha=row.getString("fecha");
                 hora=row.getString("hora");
                 factura=row.getString("factura");
                 usuario=row.getString("usuario");
                 idalquiler=row.getInt("idalquiler");
                 aprobado=row.getInt("aprobado");
                 cancelado=row.getInt("cancelado");
                 realizado=row.getInt("realizado");
                 if(aprobado!=1&&cancelado!=1){
                     solicitudes++;
                 }else if(cancelado!=1 && realizado!=1){
                     System.out.println(fecha+" "+realizado);
                 PanelSolicitud newPanel = new PanelSolicitud(nombre,telefono,cantidad,fecha,hora,factura,usuario,idalquiler,aprobado,cancelado,alquiler);
                panelSolicitudes.add(newPanel);
                 }
                 
                 if(solicitudes>0){
                     jlNotif.setEnabled(true);
                     activo=true;
                 }else{
                     jlNotif.setEnabled(false);
                     activo=false;
                 }
              
               panelSolicitudes.revalidate();
                 
            
        }
      setBackground(new java.awt.Color(204, 255, 255));
      
         
        
        panelSolicitudes.setVisible(true);
         } catch (JSONException ex) {
                 Logger.getLogger(AlquilerSurf.class.getName()).log(Level.SEVERE, null, ex);
             }
       
          
              //  MyBtnAction mba=new MyBtnAction(nombre);
             
             

    }
    /**
 * Al pulsar en el botón guardar se actualizan los precios de esa escuela
 * @param evt 
 */
    private void bGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGuardarActionPerformed
        try {
            JSONObject respuesta=cpl.setPrecios(usuarioescuela,preciohora,preciodia,"tabla surf");
            if(respuesta.getString("resultado").equals("correcto")){
                JOptionPane.showMessageDialog(this, "Datos actualizados correctamente", "CORRECTO", JOptionPane.INFORMATION_MESSAGE);
            } else{
                 JOptionPane.showMessageDialog(this, "Error al actualizar", "ERROR", JOptionPane.ERROR_MESSAGE);
             } 
        } catch (JSONException ex) {
            Logger.getLogger(AlquilerSurf.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bGuardarActionPerformed
     /**
     * Al pulsar en el botón para editar el precio del día, se pide un nuevo precio y se guarda en la variable global.
     * Se activa el botón de guardar.
     * @param evt 
     */
    private void beditaDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beditaDiaActionPerformed
        String spreciodia = JOptionPane.showInputDialog("Introduzca nuevo precio para el día completo de alquiler: ");
        if (spreciodia.equals("")) {
            JOptionPane.showMessageDialog(this, "No puede dejar el campo vacío", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            jtxPrecioDia.setText(spreciodia);
            preciodia=spreciodia;
            bGuardar.setEnabled(true);
        }
    }//GEN-LAST:event_beditaDiaActionPerformed
   /**
     * Obtiene los precios definidos por la escuela y los coloca en las cajas de texto correspondiente. Y determina el funcionamiento al pulsar el label que donde se mostrará si 
     * tenemos o no una nueva solicitud
     */
    public void colocaValores(){
        try {
            
            
            
            JSONObject respuesta=cpl.getPrecios(usuarioescuela);
            if(respuesta.getString("resultado").equals("incorrecto")){
                JOptionPane.showMessageDialog(this, "Error al recuperar datos", "Error", JOptionPane.ERROR_MESSAGE);
            }else{
                preciohora=respuesta.getString("surfhora");
                preciodia=respuesta.getString("surfdia");
                if(!preciohora.equals("0")){
                  
                    jtxPrecioHora.setText(preciohora);
                    jtxPrecioHora.setEditable(false);
                }else{
                    jtxPrecioHora.setText("No definido");
                    jtxPrecioHora.setEditable(false);
                }
                if(!preciodia.equals("0")){
                    
                    jtxPrecioDia.setText(preciodia);
                    jtxPrecioHora.setEditable(false);
                }else{
                    jtxPrecioDia.setText("No definido");
                    jtxPrecioDia.setEditable(false);
                }
                
                
               initAprobadas();
               
                  jlNotif.addMouseListener(new MouseAdapter()
            {
                public void mouseClicked(MouseEvent e)
                {
                    if(lista.equals("aprob")){
                        if(activo){
                        panelSolicitudes.removeAll();
                        initSolicitudes();
                        labelLista.setText("SOLICITUDES");
                        lista="solic";
                        jlNotif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/list.png")));
                        }
                    }else{
                        panelSolicitudes.removeAll();
                        initAprobadas();
                        labelLista.setText("APROBADAS");
                        lista="aprob";
                        jlNotif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/notification.png")));
                    }
                }
            }); 
                
            }} catch (JSONException ex) {
            Logger.getLogger(AlquilerSurf.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAtras;
    private javax.swing.JButton bGuardar;
    private javax.swing.JButton beditaDia;
    private javax.swing.JButton beditaHora;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlNotif;
    private javax.swing.JTextField jtxPrecioDia;
    private javax.swing.JTextField jtxPrecioHora;
    private javax.swing.JLabel labelLista;
    private javax.swing.JLabel labelSolicitudes;
    private javax.swing.JPanel panelSolicitudes;
    // End of variables declaration//GEN-END:variables
}
