/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import cliente.Client;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BoxLayout;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;
import protocolo.ClientProtocol;

/**
 *
 * @author pablo
 */
/**
 * Esta clase lleva la gestión de las clases colectivas de la escuela.
 * @author pablo
 */
public class ClasesColectivas extends javax.swing.JPanel {
    String usuarioescuela,nivel,descripcion,precio;
    String lista="creadas";
    ClientProtocol cpl;
    /**
     * Creates new form ClasesColectivas
     */
    public ClasesColectivas(String usuarioescuela) {
        initComponents();
        this.cpl=Client.ptl;
        this.usuarioescuela=usuarioescuela;
        colocaValores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxNivel = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxDescrip = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jtxPrecio = new javax.swing.JTextField();
        bCrear = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        panelCreadas = new javax.swing.JPanel();
        bAtras = new javax.swing.JButton();
        jlNotif = new javax.swing.JLabel();
        labelLista = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo-login.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("CLASES COLECTIVAS");

        jLabel3.setText("Nivel ");

        jLabel4.setText("Descripción (max 255):");

        jtxDescrip.setColumns(20);
        jtxDescrip.setDocument(new LimitedStyledDocument(255));
        jtxDescrip.setRows(5);

        jLabel5.setText("Precio por participante");

        bCrear.setText("Crear");
        bCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCrearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCreadasLayout = new javax.swing.GroupLayout(panelCreadas);
        panelCreadas.setLayout(panelCreadasLayout);
        panelCreadasLayout.setHorizontalGroup(
            panelCreadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        panelCreadasLayout.setVerticalGroup(
            panelCreadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 515, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(panelCreadas);

        bAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/atras.png"))); // NOI18N
        bAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAtrasActionPerformed(evt);
            }
        });

        jlNotif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/list.png"))); // NOI18N

        labelLista.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelLista.setText("CREADAS");

        jLabel6.setText("€");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(134, 134, 134)
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtxNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bCrear)
                                    .addComponent(jtxDescrip, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jtxPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel6)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bAtras)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelLista)
                        .addGap(202, 202, 202)
                        .addComponent(jlNotif)
                        .addGap(76, 76, 76))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bAtras)
                .addGap(42, 42, 42)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtxNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtxDescrip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(32, 32, 32)
                .addComponent(bCrear)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jlNotif)
                        .addGap(28, 28, 28))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(labelLista)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
    }// </editor-fold>//GEN-END:initComponents
/**
 * Al pulsar el botón atrás se vuelve al panel principal.
 * @param evt 
 */
    private void bAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAtrasActionPerformed
         PrincipalFrame f = (PrincipalFrame) SwingUtilities.windowForComponent(bAtras);
        Dimension ss = Toolkit.getDefaultToolkit().getScreenSize();
        f.setBounds(ss.width / 2 - Principal.width / 2,
                ss.height / 2 - Principal.height / 2,
                Principal.width, Principal.height);
        Principal pp = new Principal(usuarioescuela);
        f.setContentPane(pp);
        f.pack();
        f.setSize(958, 725);
        f.setVisible(true);        
    }//GEN-LAST:event_bAtrasActionPerformed

   /**
    * Este método coloca los valores iniciales, es decir en el panel de las solicitudes coloca primero las creadas y configura el label 
    * con el icono de lista para que al pulsarse se muestren las clases programadas
    */
    public void colocaValores(){
       
           initCreadas();
          jlNotif.addMouseListener(new MouseAdapter()
            {
                public void mouseClicked(MouseEvent e)
                {
                    if(lista.equals("creadas")){
                       
                        panelCreadas.removeAll();
                        initProgramadas();
                        labelLista.setText("PROGRAMADAS");
                        lista="programadas";
                        
                    }else{
                        panelCreadas.removeAll();
                        initCreadas();
                        labelLista.setText("CREADAS");
                        lista="creadas";
                    }
                }
            }); 
             
         
    }
    /**
     * Este método coloca en el panel de solicitudes las clases creadas, convirtiendo el array que le devuelve el servidor en objetos de tipo
     * JPanel que es cada hijo del panel.
     * 
     */
    public void initCreadas(){
        panelCreadas.setLayout(new BoxLayout(panelCreadas, BoxLayout.Y_AXIS));
          try {
     
         String descripcion,nivel,precio;
         int id,activa;
             JSONObject respuesta = cpl.getColectivas(Client.nombreescuela);
             JSONArray array = respuesta.getJSONArray("colectivas");
             int solicitudes=0;
             for (int i = 0; i < array.length(); i++) {
             
                 JSONObject row = array.getJSONObject(i);
                 id=row.getInt("id");
                
                 nivel=row.getString("nivel");
                 precio=row.getString("precio");
                 descripcion=row.getString("descripcion");
                 activa=row.getInt("activa");
                 if(activa!=1){
                
                 PanelColectiva newPanel = new PanelColectiva(descripcion,nivel,precio,id);
                panelCreadas.add(newPanel);
                 }
                panelCreadas.revalidate();
               
             }
        
       
        panelCreadas.setVisible(true);
                  } catch (JSONException ex) {
             Logger.getLogger(ExcursionPrincipal.class.getName()).log(Level.SEVERE, null, ex);
         }
        
    }
    
    /**
     * Este método coloca en el panel de solicitudes las clases programadas, convirtiendo el array que le devuelve el servidor en objetos de tipo
     * JPanel que es cada hijo del panel.
     * 
     */
    public void initProgramadas(){
        panelCreadas.setLayout(new BoxLayout(panelCreadas, BoxLayout.Y_AXIS));
          try {
     
         String nombre,fecha,participantes;
        
         int id,nparticipantes,activa,activaprog;
             JSONObject respuesta = cpl.getActividadesProgramadas(Client.nombreescuela,"colectiva");
             JSONArray array = respuesta.getJSONArray("actividades");
             int solicitudes=0,pactual=0;
             for (int i = 0; i < array.length(); i++) {
             
                 JSONObject row = array.getJSONObject(i);
                 id=row.getInt("id");
                 nombre=row.getString("nombre");
                 nparticipantes=row.getInt("participantes");
                 participantes=Integer.toString(nparticipantes);
                 fecha=row.getString("fecha");
                 activa=row.getInt("activa");
                 pactual=row.getInt("pactual");
                 activaprog=row.getInt("activaprog");
                 if(activa!=1 && activaprog!=1){
                 PanelExcProgramada newPanel = new PanelExcProgramada(nombre,fecha,participantes,id,pactual);
                panelCreadas.add(newPanel);
                 }
                panelCreadas.revalidate();
               
             }
        
       
        panelCreadas.setVisible(true);
                  } catch (JSONException ex) {
             Logger.getLogger(ExcursionPrincipal.class.getName()).log(Level.SEVERE, null, ex);
         }
        
    }
    /**
     * Al pulsar el botón crear se validan los datos que han de introducirse para crear una nueva excursión, si no son válidos se informa del error
     * y si son válidos se lanza una petición al servidor para que las cree
     * @param evt 
     */
    private void bCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCrearActionPerformed
        try {
            nivel = jtxNivel.getText();
            descripcion = jtxDescrip.getText();
            precio=jtxPrecio.getText();
           
            if (nivel.equals("") || descripcion.equals("") || precio.equals("")) {

                JOptionPane.showMessageDialog(this, "No puede dejar ningún campo vacío", "Error", JOptionPane.ERROR_MESSAGE);
            }else{

                JSONObject respuesta = cpl.newColectiva(nivel,descripcion, precio,  usuarioescuela);
                if (respuesta.getString("resultado").equals("incorrecto")) {
                    JOptionPane.showMessageDialog(this, "No se ha podido crear la clase", "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Clase colectiva creada", "Correcto", JOptionPane.INFORMATION_MESSAGE);
                    panelCreadas.removeAll();
                    initCreadas();
                }
            }
        } catch (JSONException ex) {
            Logger.getLogger(ExcursionPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_bCrearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAtras;
    private javax.swing.JButton bCrear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jlNotif;
    private javax.swing.JTextArea jtxDescrip;
    private javax.swing.JTextField jtxNivel;
    private javax.swing.JTextField jtxPrecio;
    private javax.swing.JLabel labelLista;
    private javax.swing.JPanel panelCreadas;
    // End of variables declaration//GEN-END:variables
}
