/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import cliente.Client;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.net.HttpURLConnection;
import java.net.URL;
import java.net.URLEncoder;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.json.JsonObject;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.border.LineBorder;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.xpath.XPath;
import javax.xml.xpath.XPathConstants;
import javax.xml.xpath.XPathExpression;
import javax.xml.xpath.XPathFactory;
import org.json.JSONException;
import org.json.JSONObject;
import org.w3c.dom.Document;
import protocolo.ClientProtocol;

/**
 *
 * @author pablo
 * En esta clase se pueden ver y cambiar los datos que tiene el usuario en el perfil, se pueden cambiar todos los datos excepto el usuario.

*/
public class ConfiguracionPerfil extends javax.swing.JPanel {

    String nombre;
    String gerente;
    String direccion;
    String descripcion;
    String latitud;
    String longitud;
    String usuario;
    boolean bcolectivas;
    boolean bindividuales;
    boolean bexcursiones;
    boolean baSurf;
    boolean baKayak;
    boolean cambiosCB;
    int colectivas;
    int individuales;
    int excursiones;
    int aSurf;
    int aKayak;
     static int width=962;
    static int height=768;

    /**
     * Creates new form ConfiguracionPerfil
     */
    public ConfiguracionPerfil(String usuario) {
        this.usuario = usuario;
        initComponents();
        rellenaCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txfNombre = new javax.swing.JTextField();
        jlabelLogo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaDescrip = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        txfDireccion = new javax.swing.JTextField();
        cbIndividuales = new javax.swing.JCheckBox();
        cbColectivas = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        cbExKayak = new javax.swing.JCheckBox();
        cbSurf = new javax.swing.JCheckBox();
        cbKayak = new javax.swing.JCheckBox();
        bGuardar = new javax.swing.JButton();
        txfGerente = new javax.swing.JTextField();
        bNombre = new javax.swing.JButton();
        bGerente = new javax.swing.JButton();
        bDireccion = new javax.swing.JButton();
        bDescripcion = new javax.swing.JButton();
        bServicios = new javax.swing.JButton();
        bAtras = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        txfNombre.setEnabled(false);
        txfNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfNombreActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("MI PERFIL");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Nombre escuela:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Nombre gerente:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Descripción (max 250):");

        jtaDescrip.setColumns(20);
        jtaDescrip.setDocument(new LimitedStyledDocument(250));
        jtaDescrip.setLineWrap(true);
        jtaDescrip.setRows(5);
        jtaDescrip.setWrapStyleWord(true);
        jtaDescrip.setEnabled(false);
        jScrollPane1.setViewportView(jtaDescrip);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Dirección:");

        txfDireccion.setEnabled(false);
        txfDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfDireccionActionPerformed(evt);
            }
        });

        cbIndividuales.setText("Clases surf individuales");
        cbIndividuales.setEnabled(false);
        cbIndividuales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbIndividualesActionPerformed(evt);
            }
        });

        cbColectivas.setText("Clases surf colectivas");
        cbColectivas.setEnabled(false);
        cbColectivas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbColectivasActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Servicios");

        cbExKayak.setText("Excursiones en kayak");
        cbExKayak.setEnabled(false);
        cbExKayak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbExKayakActionPerformed(evt);
            }
        });

        cbSurf.setText("Alquiler tablas surf");
        cbSurf.setEnabled(false);

        cbKayak.setText("Alquiler kayaks");
        cbKayak.setToolTipText("");
        cbKayak.setEnabled(false);

        bGuardar.setText("Guardar");
        bGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGuardarActionPerformed(evt);
            }
        });

        txfGerente.setEnabled(false);

        bNombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pencil.png"))); // NOI18N
        bNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNombreActionPerformed(evt);
            }
        });

        bGerente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pencil.png"))); // NOI18N
        bGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGerenteActionPerformed(evt);
            }
        });

        bDireccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pencil.png"))); // NOI18N
        bDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDireccionActionPerformed(evt);
            }
        });

        bDescripcion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pencil.png"))); // NOI18N
        bDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDescripcionActionPerformed(evt);
            }
        });

        bServicios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pencil.png"))); // NOI18N
        bServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bServiciosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(83, 83, 83))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(125, 125, 125)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txfDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txfGerente, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bGerente, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(42, 42, 42)
                                .addComponent(bNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(bDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addComponent(txfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bServicios, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(bDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbIndividuales)
                            .addComponent(cbColectivas))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cbExKayak)
                                .addGap(18, 18, 18)
                                .addComponent(cbKayak))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cbSurf)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bGuardar)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(37, 37, 37))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(270, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jlabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(235, 235, 235))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(377, 377, 377))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jlabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bNombre)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2)))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txfGerente, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bGerente)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bDescripcion))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(bServicios)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbExKayak)
                            .addComponent(cbKayak)
                            .addComponent(cbColectivas)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(bDireccion)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txfDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbSurf)
                    .addComponent(cbIndividuales))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(bGuardar)
                .addGap(44, 44, 44))
        );

        bAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/atras.png"))); // NOI18N
        bAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(bAtras)
                .addContainerGap(853, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(bAtras)
                .addContainerGap(654, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 43, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 43, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txfNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfNombreActionPerformed

    private void txfDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfDireccionActionPerformed

    private void cbIndividualesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbIndividualesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbIndividualesActionPerformed

    private void cbColectivasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbColectivasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbColectivasActionPerformed

    private void cbExKayakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbExKayakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbExKayakActionPerformed
/**
 * Este método coloca en las cajas de texto los valores que ya se encuentran guardados del usuario en la base de datos
 */
    public void rellenaCampos() {
        try {
            ClientProtocol cpl = Client.getClientProtocol();
            JSONObject respuesta = cpl.datosEscuela(usuario);
            if (respuesta.getString("resultado").equals("incorrecto")) {
                JOptionPane.showMessageDialog(this, "Error al recuperar datos", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                nombre = respuesta.getString("nombre");
                gerente = respuesta.getString("gerente");
                latitud = respuesta.getString("latitud");
                longitud = respuesta.getString("longitud");
                direccion = respuesta.getString("direccion");
                descripcion = respuesta.getString("descripcion");
                colectivas = respuesta.getInt("colectivas");
                individuales = respuesta.getInt("individuales");
                excursiones = respuesta.getInt("excursiones");
                aKayak = respuesta.getInt("alquilerkayak");
                aSurf = respuesta.getInt("alquilersurf");
                if (colectivas == 1) {
                    cbColectivas.setSelected(true);
                    bcolectivas = true;
                } else {
                    bcolectivas = false;
                }
                if (individuales == 1) {
                    cbIndividuales.setSelected(true);
                    bindividuales = true;
                } else {
                    bindividuales = true;
                }
                
                if (excursiones == 1) {
                    cbExKayak.setSelected(true);
                    bexcursiones = true;
                } else {
                    bexcursiones = false;
                }
                if (aKayak == 1) {
                    cbKayak.setSelected(true);
                    baKayak = true;
                } else {
                    baKayak = false;
                }
                if (aSurf == 1) {
                    cbSurf.setSelected(true);
                    baSurf = true;
                } else {
                    baSurf = false;
                }
                txfNombre.setText(nombre);
                txfGerente.setText(gerente);
                txfDireccion.setText(direccion);
                jtaDescrip.setText(descripcion);
                
            }
        } catch (JSONException ex) {
            Logger.getLogger(ConfiguracionPerfil.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * Al guardar se validan los datos y si son correctos se actualizan en la BD
     * @param evt 
     */
    private void bGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGuardarActionPerformed
        bcolectivas = cbColectivas.isSelected();
        bindividuales = cbIndividuales.isSelected();
        bexcursiones = cbExKayak.isSelected();
        baKayak = cbKayak.isSelected();
        baSurf = cbSurf.isSelected();
        //validaciones campos texto
        if (nombre.equals("") || gerente.equals("") || direccion.equals("") || descripcion.equals("")) {
            JOptionPane.showMessageDialog(this, "No puede dejar ningún campo en blanco", "Error", JOptionPane.ERROR_MESSAGE);
            //validaciones checkbox
        } else if (bcolectivas == false && bindividuales == false && bexcursiones == false && baKayak == false && baSurf == false) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar al menos un servicio", "Error", JOptionPane.ERROR_MESSAGE);
        } else {

            try {
                ClientProtocol ptl = Client.getClientProtocol();
                JSONObject respuesta = ptl.actualiza(nombre, gerente, latitud, longitud, direccion, descripcion, usuario, bcolectivas, bindividuales, bexcursiones, baKayak, baSurf);
                System.out.println(respuesta);
                String srespuesta = respuesta.getString("resultado");
                
                if (srespuesta.equals("correcto")) {
                    JOptionPane.showMessageDialog(this, "Actualizado correctamente !", "Actualización correcta", JOptionPane.INFORMATION_MESSAGE);
                    PrincipalFrame f = (PrincipalFrame) SwingUtilities.windowForComponent(bAtras);
                    Dimension ss = Toolkit.getDefaultToolkit().getScreenSize();
                    f.setBounds(ss.width / 2 - Principal.width/ 2,
                            ss.height / 2 - Principal.height / 2,
                            Principal.width, Principal.height);
                    Principal pp = new Principal(usuario);
                    f.setContentPane(pp);
                    f.pack();
                    f.setVisible(true);
                    
                }
            } catch (JSONException ex) {
                Logger.getLogger(ConfiguracionPerfil.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_bGuardarActionPerformed
/**
 * Si pulsamos el botón de atrás iremos al panel principal
 * @param evt 
 */
    private void bAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAtrasActionPerformed
        PrincipalFrame f = (PrincipalFrame) SwingUtilities.windowForComponent(bAtras);
         Dimension ss = Toolkit.getDefaultToolkit().getScreenSize();
                f.setBounds(ss.width / 2 - Principal.width/ 2,
                    ss.height / 2 - Principal.height / 2,
                    Principal.width, Principal.height);
        Principal pp = new Principal(usuario);
        f.setContentPane(pp);
        f.pack();
        f.setSize(958, 725);
        f.setVisible(true);
    }//GEN-LAST:event_bAtrasActionPerformed
/**
 * Cada vez que se pulsa el botón editar de cada uno de los campos, se abre un dialog que nos pide que introduzcamos el nuevo valor.
 * @param evt 
 */
    private void bNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNombreActionPerformed
        nombre = JOptionPane.showInputDialog("Introduzca nuevo nombre de la escuela: ");
        if (nombre.equals("")) {
            JOptionPane.showMessageDialog(this, "No puede dejar el campo vacío", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            txfNombre.setText(nombre);
        }


    }//GEN-LAST:event_bNombreActionPerformed

    private void bGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGerenteActionPerformed
        gerente = JOptionPane.showInputDialog("Introduzca nuevo nombre de gerente: ");
        if (gerente.equals("")) {
            JOptionPane.showMessageDialog(this, "No puede dejar el campo vacío", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            txfGerente.setText(gerente);
        }


    }//GEN-LAST:event_bGerenteActionPerformed

    private void bDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDireccionActionPerformed
        direccion = JOptionPane.showInputDialog("Introduzca nueva dirección: ");
        String[] latlong = new String[2];
        try {
            latlong = obtenerLatLong(direccion);

            txfDireccion.setText(direccion);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Dirección incorrecta", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bDireccionActionPerformed

    private void bDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDescripcionActionPerformed
        descripcion = JOptionPane.showInputDialog("Introduzca nueva descripción: ");
        if (descripcion.equals("")) {
            JOptionPane.showMessageDialog(this, "No puede dejar el campo vacío", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            jtaDescrip.setText(descripcion);
        }
    }//GEN-LAST:event_bDescripcionActionPerformed

    private void bServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bServiciosActionPerformed
        cambiosCB = true;
        cbColectivas.setEnabled(true);
        cbExKayak.setEnabled(true);
        cbIndividuales.setEnabled(true);
        cbKayak.setEnabled(true);
        cbSurf.setEnabled(true);
    }//GEN-LAST:event_bServiciosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAtras;
    private javax.swing.JButton bDescripcion;
    private javax.swing.JButton bDireccion;
    private javax.swing.JButton bGerente;
    private javax.swing.JButton bGuardar;
    private javax.swing.JButton bNombre;
    private javax.swing.JButton bServicios;
    private javax.swing.JCheckBox cbColectivas;
    private javax.swing.JCheckBox cbExKayak;
    private javax.swing.JCheckBox cbIndividuales;
    private javax.swing.JCheckBox cbKayak;
    private javax.swing.JCheckBox cbSurf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlabelLogo;
    private javax.swing.JTextArea jtaDescrip;
    private javax.swing.JTextField txfDireccion;
    private javax.swing.JTextField txfGerente;
    private javax.swing.JTextField txfNombre;
    // End of variables declaration//GEN-END:variables
public String[] obtenerLatLong(String address) throws Exception {

        String latlong[] = new String[2];
        int responseCode = 0;
        String api = "http://maps.googleapis.com/maps/api/geocode/xml?address=" + URLEncoder.encode(address, "UTF-8") + "&sensor=true";
        URL url = new URL(api);
        HttpURLConnection httpConnection = (HttpURLConnection) url.openConnection();
        httpConnection.connect();
        responseCode = httpConnection.getResponseCode();
        if (responseCode == 200) {
            DocumentBuilder builder = DocumentBuilderFactory.newInstance().newDocumentBuilder();;
            Document document = builder.parse(httpConnection.getInputStream());
            XPathFactory xPathfactory = XPathFactory.newInstance();
            XPath xpath = xPathfactory.newXPath();
            XPathExpression expr = xpath.compile("/GeocodeResponse/status");
            String status = (String) expr.evaluate(document, XPathConstants.STRING);
            if (status.equals("OK")) {
                expr = xpath.compile("//geometry/location/lat");
                String latitude = (String) expr.evaluate(document, XPathConstants.STRING);
                expr = xpath.compile("//geometry/location/lng");
                String longitude = (String) expr.evaluate(document, XPathConstants.STRING);
                latlong[0] = latitude;
                latlong[1] = longitude;
                return latlong;
            } else {
                throw new Exception("Error al obtener la latitud y longitud");

            }
        }
        return latlong;
    }

}
