/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import cliente.Client;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.json.JsonObject;
import javax.swing.Icon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import org.json.JSONException;
import org.json.JSONObject;
import protocolo.ClientProtocol;

/**
 *
 * @author pablo
 * Esta clase es el login del programa, primera interfaz que se muestra al iniciar la aplicacion
 */
public class Login extends javax.swing.JPanel {

    /**
     * Creates new form Login
     */
    
    static int width=321;
    static int height=435;
    public Login() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txfUsuario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txfContraseña = new javax.swing.JPasswordField();
        bIniciarSesion = new javax.swing.JButton();
        bRegistrarse = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setBackground(new java.awt.Color(204, 255, 255));

        jLabel3.setText("Usuario:");

        jLabel4.setText("Contraseña:");

        bIniciarSesion.setText("Iniciar sesión");
        bIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIniciarSesionActionPerformed(evt);
            }
        });

        bRegistrarse.setText("Registrarse");
        bRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRegistrarseActionPerformed(evt);
            }
        });

        jButton1.setText("Cambiar servidor");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo-login.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bRegistrarse)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                .addComponent(txfContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(28, 28, 28)
                                        .addComponent(txfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel5))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(bIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(38, 38, 38)))))
                        .addGap(44, 44, 44))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel5)))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(49, 49, 49)
                .addComponent(bIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bRegistrarse)
                    .addComponent(jButton1))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
/**
 * Si se pulsa en el boton de registrarse se muestra la pantalla de registro
 * @param evt 
 */
    private void bRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRegistrarseActionPerformed
        JFrame f = (JFrame) SwingUtilities.windowForComponent(bIniciarSesion);
         Dimension ss = Toolkit.getDefaultToolkit().getScreenSize();
         f.setBounds(ss.width / 2 - ConfiguracionPerfil.width/ 2,
                            ss.height / 2 - ConfiguracionPerfil.height / 2,
                            ConfiguracionPerfil.width, ConfiguracionPerfil.height);
        Registro registro = new Registro();
        f.setContentPane(registro);
        f.pack();
        f.setSize(958, 725);
        f.setVisible(true);
        f.setResizable(false);
    }//GEN-LAST:event_bRegistrarseActionPerformed
/*
    Si se pulsa en iniciar sesión, se comprueba que no haya ningún campo vacío y se hace una petición al servidor para comprobar
    si es correcto o no el usuario y contraseña. Si es correcto se pasa a la pantalla principal de esa escuela.
    */
    private void bIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIniciarSesionActionPerformed
        try {
            String usuario=txfUsuario.getText();
            String contraseña = String.valueOf(txfContraseña.getPassword());
            ClientProtocol cpl=Client.getClientProtocol();
            JSONObject respuesta=cpl.login(usuario, contraseña);
            String srespuesta=respuesta.getString("resultado");
            if (srespuesta.equals("correcto")) {
                JOptionPane.showMessageDialog(this, "Inicio de sesión realizado correctamente", "Iniciar sesión", JOptionPane.INFORMATION_MESSAGE);
                
                PrincipalFrame f = (PrincipalFrame) SwingUtilities.windowForComponent(bIniciarSesion);
                Dimension ss = Toolkit.getDefaultToolkit().getScreenSize();
                f.setBounds(ss.width / 2 - ConfiguracionPerfil.width/ 2,
                            ss.height / 2 - ConfiguracionPerfil.height / 2,
                            ConfiguracionPerfil.width, ConfiguracionPerfil.height);
                Principal pl = new Principal(usuario);
                f.setContentPane(pl);
                f.setVisible(true);
                f.setResizable(false);
            }else{
                JOptionPane.showMessageDialog(this, "Usuario o contraseña no válido", "Error", JOptionPane.ERROR_MESSAGE);
            }} catch (JSONException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bIniciarSesionActionPerformed
/*
    Al pulsar en el botón de cambiar de servidor, nos da la opción de cambiar la ip y servidor de la aplicación.
    */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String ip= JOptionPane.showInputDialog("Introduzca nueva ip ");
        String sport= JOptionPane.showInputDialog("Introduzca nuevo puerto");
        int port=Integer.parseInt(sport);
        
        Client.cambiaConf(ip, port);
         PrincipalFrame f = (PrincipalFrame) SwingUtilities.windowForComponent(bIniciarSesion);
         f.dispose();
        try {
            Client.main(null);
        } catch (IOException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bIniciarSesion;
    private javax.swing.JButton bRegistrarse;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField txfContraseña;
    private javax.swing.JTextField txfUsuario;
    // End of variables declaration//GEN-END:variables

}
