/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import cliente.Client;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BoxLayout;
import javax.swing.SwingUtilities;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;
import protocolo.ClientProtocol;

/**
 *
 * @author pablo
 * En este panel se muestran las notificaciones de tiempo de la aplicación
 * A este método solo se puede acceder cuando hay alguna notificación de tiempo (controlado en el panel Principal)
 */
public class Notificaciones extends javax.swing.JPanel {
    ClientProtocol cpl;
    String usuarioescuela;
    static int width=755;
    static int height=768;

    /**
     * Creates new form Notificaciones
     */
    public Notificaciones(String usuarioescuela) {
        this.usuarioescuela=usuarioescuela;
        cpl=Client.getClientProtocol();
        initComponents();
        initNotificaciones();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelNotif = new javax.swing.JPanel();
        bAtras = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo-login.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("NOTIFICACIONES TIEMPO");

        javax.swing.GroupLayout panelNotifLayout = new javax.swing.GroupLayout(panelNotif);
        panelNotif.setLayout(panelNotifLayout);
        panelNotifLayout.setHorizontalGroup(
            panelNotifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 559, Short.MAX_VALUE)
        );
        panelNotifLayout.setVerticalGroup(
            panelNotifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 545, Short.MAX_VALUE)
        );

        bAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/atras.png"))); // NOI18N
        bAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelNotif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(bAtras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(110, 110, 110))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(bAtras))
                .addGap(18, 18, 18)
                .addComponent(panelNotif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
/**
 * Si se pulsa en el botón de atrás se vuelve al panel principal
 * @param evt 
 */
    private void bAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAtrasActionPerformed
            PrincipalFrame f = (PrincipalFrame) SwingUtilities.windowForComponent(bAtras);
        Dimension ss = Toolkit.getDefaultToolkit().getScreenSize();
        f.setBounds(ss.width / 2 - Principal.width / 2,
                ss.height / 2 - Principal.height / 2,
                Principal.width, Principal.height);
        Principal pp = new Principal(usuarioescuela);
        f.setContentPane(pp);
        f.pack();
        f.setSize(958, 725);
        f.setVisible(true);       
    }//GEN-LAST:event_bAtrasActionPerformed
   /**
    * Se obtiene las notificaciones que tenga la escuela y se crea un objeto panel por cada una para mostrarlo en forma de lista en el panel de
    * este panel.
    */
    public void initNotificaciones(){
          panelNotif.setLayout(new BoxLayout(panelNotif, BoxLayout.Y_AXIS));
          try {
     
         String nombre,viento,lluvia,descripcion,pviento,plluvia,fecha;
         int id;
             JSONObject respuesta = cpl.getAlertas(Client.nombreescuela);
             JSONArray array = respuesta.getJSONArray("excursiones");
             int solicitudes=0;
             for (int i = 0; i < array.length(); i++) {
             
                 JSONObject row = array.getJSONObject(i);
                 id=row.getInt("id");
                 nombre=row.getString("nombre");
                 viento=row.getString("vientomax");
                 lluvia=row.getString("poslluvia");
                 pviento=row.getString("pviento");
                 plluvia=row.getString("plluvia");
                 fecha=row.getString("fecha");
                 descripcion=row.getString("descripcion");
                 
                 PanelNotificacion newPanel = new PanelNotificacion(nombre,descripcion,viento,lluvia,pviento,plluvia,fecha,id);
                panelNotif.add(newPanel);
                panelNotif.revalidate();
                 
               
             }
        
       
        panelNotif.setVisible(true);
                  } catch (JSONException ex) {
             Logger.getLogger(ExcursionPrincipal.class.getName()).log(Level.SEVERE, null, ex);
         }
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAtras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel panelNotif;
    // End of variables declaration//GEN-END:variables
}
