/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;
import cliente.Client;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.net.URLConnection;
import java.net.HttpURLConnection;
import java.net.URL;
import java.net.URLEncoder;
import java.io.InputStreamReader;
import java.io.BufferedReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.json.JsonObject;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.xpath.XPath;
import javax.xml.xpath.XPathExpression;
import javax.xml.xpath.XPathFactory;
import javax.xml.xpath.XPathConstants;
import org.json.JSONException;
import org.json.JSONObject;
import org.w3c.dom.Document;
import protocolo.ClientProtocol;

/**
 *
 * @author pablo
 */
public class Registro extends javax.swing.JPanel {

    /**
     * Esta clase contiene la interfaz y la gestión del registro de los usuarios de las escuelas
     */
    
    static int width=958;
    static int height=725;
    public Registro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txfNombre = new javax.swing.JTextField();
        jlabelLogo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaDescrip = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        txfDireccion = new javax.swing.JTextField();
        cbIndividuales = new javax.swing.JCheckBox();
        cbColectivas = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        cbExKayak = new javax.swing.JCheckBox();
        cbSurf = new javax.swing.JCheckBox();
        cbKayak = new javax.swing.JCheckBox();
        bRegistrarse = new javax.swing.JButton();
        bLimpiar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txfGerente = new javax.swing.JTextField();
        txfContraseña = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        txfUsuario = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        bAtras = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 255));

        txfNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfNombreActionPerformed(evt);
            }
        });

        jlabelLogo.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("REGISTRO");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Nombre escuela:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Nombre gerente:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Descripción (max 250):");

        jtaDescrip.setColumns(20);
        jtaDescrip.setDocument(new LimitedStyledDocument(250));
        jtaDescrip.setLineWrap(true);
        jtaDescrip.setRows(5);
        jtaDescrip.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jtaDescrip);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Dirección:");

        txfDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfDireccionActionPerformed(evt);
            }
        });

        cbIndividuales.setText("Clases surf individuales");
        cbIndividuales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbIndividualesActionPerformed(evt);
            }
        });

        cbColectivas.setText("Clases surf colectivas");
        cbColectivas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbColectivasActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Servicios");

        cbExKayak.setText("Excursiones en kayak");
        cbExKayak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbExKayakActionPerformed(evt);
            }
        });

        cbSurf.setText("Alquiler tablas surf");

        cbKayak.setText("Alquiler kayaks");
        cbKayak.setToolTipText("");

        bRegistrarse.setText("Registrarse");
        bRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRegistrarseActionPerformed(evt);
            }
        });

        bLimpiar.setText("Limpiar");
        bLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLimpiarActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Contraseña:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Usuario:");

        bAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/atras.png"))); // NOI18N
        bAtras.setToolTipText("");
        bAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAtrasActionPerformed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo-login.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel8))
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(83, 83, 83))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(125, 125, 125)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txfDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txfGerente, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 421, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1))))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbIndividuales)
                            .addComponent(cbColectivas))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbExKayak)
                                .addGap(18, 18, 18)
                                .addComponent(cbKayak))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(bLimpiar)
                                    .addComponent(cbSurf))
                                .addGap(56, 56, 56)
                                .addComponent(bRegistrarse)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txfContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(229, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(184, 184, 184))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(235, 235, 235))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(bAtras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(377, 377, 377))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bAtras)))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txfContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txfGerente, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbExKayak)
                            .addComponent(cbKayak)
                            .addComponent(cbColectivas)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txfDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5))
                            .addComponent(jLabel6))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbSurf)
                    .addComponent(cbIndividuales))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bRegistrarse)
                    .addComponent(bLimpiar))
                .addGap(54, 54, 54))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txfNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfNombreActionPerformed

    private void txfDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfDireccionActionPerformed

    private void cbIndividualesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbIndividualesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbIndividualesActionPerformed

    private void cbColectivasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbColectivasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbColectivasActionPerformed

    private void cbExKayakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbExKayakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbExKayakActionPerformed
/**
 * Si pulsamos en registrarse se validan los datos, y si son correctos se insertan en la BD mediante una petición al servidor
 * @param evt 
 */
    private void bRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRegistrarseActionPerformed
        String nombre = txfNombre.getText();
        String gerente = txfGerente.getText();
        String direccion = txfDireccion.getText();
        String contrasena = String.valueOf(txfContraseña.getPassword());
        String descripcion = jtaDescrip.getText();
        String usuario = txfUsuario.getText();
        boolean colectivas = cbColectivas.isSelected();
        boolean individuales = cbIndividuales.isSelected();
        boolean exkayak = cbExKayak.isSelected();
        boolean kayak = cbKayak.isSelected();
        boolean surf = cbSurf.isSelected();
        String latlong[] = null;
        //validaciones campos texto
        if (nombre.equals("") || gerente.equals("") || direccion.equals("") || contrasena.equals("") || descripcion.equals("") || usuario.equals("")) {
            
        //validaciones checkbox
        } else if (colectivas == false && individuales == false && exkayak == false && kayak == false && surf == false) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar al menos un servicio", "Error", JOptionPane.ERROR_MESSAGE);
        } else {

            try {
        //obtención latitud y longitud
                latlong = obtenerLatLong(direccion);
           

            ClientProtocol ptl = Client.getClientProtocol();
            JSONObject respuesta = ptl.registro(nombre, gerente, latlong[0], latlong[1], direccion, descripcion, usuario, contrasena, colectivas, individuales, exkayak, kayak, surf);
            System.out.println(respuesta);
            String srespuesta = respuesta.getString("resultado");
            if (srespuesta.equals("yaexiste")) {
                JOptionPane.showMessageDialog(this, "Ya existe una escuela con ese usuario, nombre o dirección. No generalice en la dirección.", "Error", JOptionPane.ERROR_MESSAGE);
            }
            if (srespuesta.equals("correcto")) {
                JOptionPane.showMessageDialog(this, "Registrado correctamente !", "Registro correcto", JOptionPane.INFORMATION_MESSAGE);
                PrincipalFrame f = (PrincipalFrame) SwingUtilities.windowForComponent(bLimpiar);
                Dimension ss = Toolkit.getDefaultToolkit().getScreenSize();
                f.setBounds(ss.width / 2 - Login.width/ 2,
                    ss.height / 2 - Login.height / 2,
                    Login.width, Login.height);
                Login lg = new Login();
                f.setContentPane(lg);
                f.pack();
                f.setSize(321,435);
                f.setVisible(true);
                f.setResizable(false);
            }
            } catch (JSONException ex) {
                    Logger.getLogger(Registro.class.getName()).log(Level.SEVERE, null, ex);
                
            } catch (Exception ex) {
                System.out.println(ex.toString());
                JOptionPane.showMessageDialog(this, "Dirección incorrecta", "Error", JOptionPane.ERROR_MESSAGE);
            
            }
        }
    }//GEN-LAST:event_bRegistrarseActionPerformed
/**
 * Si pulsamos en limpiar se vacian todos los campos
 * @param evt 
 */
    private void bLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLimpiarActionPerformed
       txfNombre.setText("");
       txfGerente.setText("");
       txfDireccion.setText("");
       txfContraseña.setText("");
       jtaDescrip.setText("");
       txfUsuario.setText("");
       cbColectivas.setSelected(false);
       cbExKayak.setSelected(false);
       cbIndividuales.setSelected(false);
       cbKayak.setSelected(false);
       cbSurf.setSelected(false);
    }//GEN-LAST:event_bLimpiarActionPerformed
/**
 * Si pulsamos el botón de atrás volvemos al login
 * @param evt 
 */
    private void bAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAtrasActionPerformed
       PrincipalFrame f = (PrincipalFrame) SwingUtilities.windowForComponent(bLimpiar);
       Dimension ss = Toolkit.getDefaultToolkit().getScreenSize();
                f.setBounds(ss.width / 2 - Login.width/ 2,
                    ss.height / 2 - Login.height / 2,
                    Login.width, Login.height);
                Login lg = new Login();
                f.setContentPane(lg);
                f.pack();
                f.setSize(321,435);
                f.setVisible(true);
                f.setResizable(false);
    }//GEN-LAST:event_bAtrasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAtras;
    private javax.swing.JButton bLimpiar;
    private javax.swing.JButton bRegistrarse;
    private javax.swing.JCheckBox cbColectivas;
    private javax.swing.JCheckBox cbExKayak;
    private javax.swing.JCheckBox cbIndividuales;
    private javax.swing.JCheckBox cbKayak;
    private javax.swing.JCheckBox cbSurf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel jlabelLogo;
    private javax.swing.JTextArea jtaDescrip;
    private javax.swing.JPasswordField txfContraseña;
    private javax.swing.JTextField txfDireccion;
    private javax.swing.JTextField txfGerente;
    private javax.swing.JTextField txfNombre;
    private javax.swing.JTextField txfUsuario;
    // End of variables declaration//GEN-END:variables
   /**
    * Con este método comprobamos que google pueda obtener la dirección 
    * @param address
    * @return
    * @throws Exception 
    */
    public String[] obtenerLatLong(String address) throws Exception{
       
      String latlong[]=new String[2];
         int responseCode = 0;
    String api = "http://maps.googleapis.com/maps/api/geocode/xml?address=" + URLEncoder.encode(address, "UTF-8") + "&sensor=true";
    URL url = new URL(api);
    HttpURLConnection httpConnection = (HttpURLConnection)url.openConnection();
    httpConnection.connect();
    responseCode = httpConnection.getResponseCode();
    if(responseCode == 200)
    {
      DocumentBuilder builder = DocumentBuilderFactory.newInstance().newDocumentBuilder();;
      Document document = builder.parse(httpConnection.getInputStream());
      XPathFactory xPathfactory = XPathFactory.newInstance();
      XPath xpath = xPathfactory.newXPath();
      XPathExpression expr = xpath.compile("/GeocodeResponse/status");
      String status = (String)expr.evaluate(document, XPathConstants.STRING);
      if(status.equals("OK"))
      {
         expr = xpath.compile("//geometry/location/lat");
         String latitude = (String)expr.evaluate(document, XPathConstants.STRING);
         expr = xpath.compile("//geometry/location/lng");
         String longitude = (String)expr.evaluate(document, XPathConstants.STRING);
         latlong[0]=latitude;
         latlong[1]=longitude;
         return latlong;
      }
      else
      {
          throw new Exception("Error al obtener la latitud y longitud");
      
      }
    }
    return latlong;
    }

}
